### ISSUE TITLE
Objective C?

### ISSUE THREAD

**Issue by gerchicov-bp** [daisuke0131/ViewMonitor#20]
Could you explain how to import it into a ready Objective-C project. When I try it shows a lot of errors. Maybe it is because I need a specific swift/xcode version you didn't mention

**Comment by yuhua-chen** [comment]
Should work by #21. And Don't forget to import header `#import "YourProjectName-Swift.h"`

**Comment by daisuke0131** [comment]
This library supported Objective-c project from 1.0.9.
1.0.9 is now released!
- updated README
- added Objective-C project example. /Example/ViewMonitorObjcExample

Thank you for your good information.
