### ISSUE TITLE
run the demo,but some error

### ISSUE THREAD

**Issue by xclidongbo** [daisuke0131/ViewMonitor#24]
"ViewMonitorObjcExample-Swift.h" file not found

**Comment by daisuke0131** [comment]
@xclidongbo 
I'm sorry.
fix the bug in this commit.
https://github.com/daisuke0131/ViewMonitor/commit/488ca52421dcbec279883ebe5368380799020835

Could you check it?

**Comment by xclidongbo** [comment]
Thx, It's run.

**Comment by daisuke0131** [comment]
thanks!
